weights: ..\yolov5s.pt
cfg: ../yolo_train_004.yaml
data: ../yolo_train_003.yaml
hyp: data/hyp.scratch.yaml
epochs: 3
batch_size: 16
img_size:
- 280
- 280
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: fedex_4www
exist_ok: false
quad: false
linear_lr: false
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs\train\fedex_4www
total_batch_size: 16
